[package]
name = "aoc1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name="aoc1"
path="src/aoc1.rs"

[dev-dependencies]
itertools = "*"
